In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])


c = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
c[0, 0:6:2]

c[1,5] = 20
c[1, 0:6] = [20]

d = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
np.full((5,5),1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.random.randint(0,2, size=(5,5))

array([[1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
result = np.ones((5,5))
result[1:4,1:4] = np.zeros((3,3))
result[2,2] = 9
print(result)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


Maths

In [ ]:
a = np.array([1,2,3,4])
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [ ]:
b = np.array([1,0,1,0])
print(a + b)
print(a ** b)
print(np.sin(a))
print(np.cos(a))

[2 2 4 4]
[1 1 3 1]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats))
print(np.max(stats))
print(np.sum(stats))

1
6
21


In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:


array = np.random.randint(1,100, size=(5,5))
print(array)
array[[0,1,2,3],[1,2,3,4]]

[[43 28 39  2 90]
 [36  9 55 93 35]
 [79 16 77 71 84]
 [87 58 79  4 25]
 [36 49 58 61 25]]


array([28, 55, 71, 25])